export const MockMeta = {
  entity: 'customObject2s',
  entityMetaUrl: '',
  label: 'NTQ',
  fields: [
    {
      name: 'float1',
      type: 'float',
      label: 'Total Years of Experience',
      required: true,
      sortOrder: 10,
      maxLength: 10,
      description: 'How long have you been nursing?',
    },
    // {
    //   name: 'lastName',
    //   type: 'text',
    //   label: 'Name',
    //   hint: 'Last Name, Yo!',
    //   description: 'Last Name, Yo!',
    //   sortOrder: 10,
    // },
    // {
    //   name: 'groupedItems',
    //   type: 'group',
    //   label: 'Groupd Items',
    //   sortOrder: 11,
    //   icon: 'section',
    //   fields: [
    //     {
    //       name: 'label',
    //       type: 'text',
    //       label: 'Label',
    //       sortOrder: 10,
    //       maxLength: 10,
    //     },
    //     {
    //       name: 'description',
    //       type: 'text',
    //       label: 'Description',
    //       sortOrder: 20,
    //     },
    //   ],
    // },
    {
      name: 'text1',
      type: 'picker',
      dataType: 'String',
      maxLength: 200,
      confidential: false,
      label: 'Specialty',
      required: true,
      readOnly: false,
      multiValue: true,
      inputType: 'SELECT',
      // TODO: Align picker with META by passing META obj into picker
      // options: [ /* flat array of states */ ]
      options: {
        options: [
          'Critical Care - ICU',
          'Emergency Room',
          'Labor & Deliver',
          'Cath-Vasc Lab',
        ],
      },
      sortOrder: 20,
    },
    {
      inputType: 'RADIO',
      label: 'Travel Experience',
      maxLength: 100,
      multiValue: false,
      name: 'radio1',
      optional: true,
      options: [
        {
          value: 'Yes',
          label: 'Yes',
        },
        {
          value: 'No',
          label: 'No',
        },
      ],
      required: true,
      sortOrder: 30,
    },
    {
      name: 'float2',
      type: 'float',
      label: 'Years of Travel Experience',
      required: true,
      sortOrder: 40,
      description: 'How long have you been traveling?',
    },
    {
      name: 'text2',
      type: 'text',
      label: 'Agency/Submissions',
      required: true,
      description: 'Which agencies are you working with? Where have you been submitted?',
      sortOrder: 50,
    },
    {
      inputType: 'RADIO',
      label: 'Backouts / Terms',
      maxLength: 100,
      multiValue: false,
      name: 'radio2',
      description: 'Has an assignment ever ended early? What happened? Are you welcome back? Will you be able to provide a reference?',
      optional: true,
      options: [
        {
          value: 'Yes',
          label: 'Yes',
        },
        {
          value: 'No',
          label: 'No',
        },
      ],
      required: true,
      sortOrder: 60,
    },
    {
      name: 'text3',
      type: 'text',
      label: 'Motivation/Why',
      required: true,
      description: 'What interests you about Traveling? What Do you like about it? What are your top 3 motivating factors? Why are you interested in and/or actively working as a Travel RN? ',
      sortOrder: 70,
    },
    {
      name: 'text4',
      type: 'text',
      label: 'Current Job & Location',
      required: true,
      description: 'Where do you currently work? Location? How long have you been there? Specialty? Unit bed count? Ratio? Level Trauma? Teaching Facility? EMR?',
      sortOrder: 80,
    },
    {
      name: 'text5',
      type: 'picker',
      dataType: 'String',
      maxLength: 300,
      confidential: false,
      label: 'EMR',
      required: true,
      readOnly: false,
      multiValue: true,
      description: 'What systems have you used (EPIC, Cerner, Meditech, McKesson to name a few)? SuperUser? Worked a conversion?',
      inputType: 'SELECT',
      // TODO: Align picker with META by passing META obj into picker
      // options: [ /* flat array of states */ ]
      options: {
        options: [
          'Cerner',
          'Epic',
          'Meditech',
          'McKesson',
        ],
      },
      sortOrder: 90,
    },
    {
      name: 'text6',
      type: 'text',
      label: 'License(s):',
      required: true,
      description: 'What states are licensed to work in? Any expired licenses? Would you be willing to obtain a new licensure for the right assignment? Compact license?',
      sortOrder: 95,
    },
    {
      name: 'text7',
      type: 'text',
      label: 'Certifications:',
      required: true,
      description: 'What certifications do you currently have? Any expired/lapsed? Would you be willing to get additional certs for the right assignment? Are they AHA?',
      sortOrder: 95,
    },
    {
      name: 'date1',
      type: 'date',
      label: 'Earliest Start Date',
      required: true,
      sortOrder: 100,
      dateFormat: 'ddd MMM DD, YYYY', // Add this to your MetaData to override the dateFormat
      defaultValue: new Date(Date.now() + 12096e5),
    },
    {
      name: 'date2',
      type: 'date',
      label: 'Latest Start Date',
      required: true,
      sortOrder: 105,
      description: 'If you got an offer this week, what is the latest start date you would accept?',
      dateFormat: 'ddd MMM DD, YYYY', // Add this to your MetaData to override the dateFormat
      defaultValue: new Date(Date.now() + 12096e5),
    },
    {
      name: 'text8',
      type: 'text',
      label: 'Shift/Duration / Schedule:',
      required: true,
      description: 'Duration: 13 weeks? Shorter/longer? (Most Assignments are 13 weeks) Schedule: 3-12’s? Weekends? Shift: Days or Nights? 8/10/12?',
      sortOrder: 110,
    },
    {
      name: 'text9',
      type: 'text',
      label: 'RTO',
      required: true,
      description: 'Do you have any time off requests? (Must be called out before submission)',
      sortOrder: 120,
    },
    {
      name: 'text10',
      type: 'text',
      label: 'Preferred Location(s):',
      required: true,
      description: 'Where are you looking to go? Anywhere you won’t go? Specific Cities of interest? Specific Hospitals of interest? (Level I, Teaching Hospitals)',
      sortOrder: 125,
    },
    {
      name: 'float3',
      type: 'money',
      label: 'Desired Pay:',
      currencyFormat: 'USD',
      description: 'Weekly gross expectations? (push them to give you a low/high range)',
      required: true,
      sortOrder: 130,
    },
    {
      inputType: 'RADIO',
      label: 'Benefits',
      maxLength: 100,
      multiValue: false,
      name: 'radio2',
      optional: true,
      description: 'Do they need Health Insurance?',
      options: [
        {
          value: 'Yes',
          label: 'Yes',
        },
        {
          value: 'No',
          label: 'No',
        },
        {
          value: 'Undecided',
          label: 'Undecided',
        },
      ],
      required: true,
      sortOrder: 135,
    },
    {
      name: 'text11',
      type: 'text',
      label: 'Communication:',
      required: true,
      description: 'Phone / Text /Email?  It is critical to the professional process and we want to know the best way to communicate with you on the day-to-day.',
      sortOrder: 140,
    },
    {
      name: 'text12',
      type: 'text',
      label: 'Perm Tax Address',
      required: true,
      description: 'Do you have a perm tax address? Where is it located?',
      sortOrder: 150,
    },
    {
      name: 'text13',
      type: 'text',
      label: 'Background check / DMV / Drug Screen / License Infractions',
      required: true,
      description: 'Background check: Is there anything that I need to know about now on the front end that would surface during a background check?',
      sortOrder: 150,
    },
    {
      name: 'text14',
      type: 'text',
      label: 'Work Schedule',
      required: true,
      description: 'What does your schedule look like this week? Next week? Any days you know you won’t be available i.e. an upcoming trip/vacation? How can we get a hold of you during work if something urgent comes up (i.e. perfect job match)?',
      sortOrder: 160,
    },
    {
      name: 'text15',
      type: 'text',
      label: 'Profile Items',
      required: true,
      description: 'Playback what they just said they were looking for to motivate them to want to do the profile items, then list them out, get a commitment based on their availability, set a completion date, and schedule a follow-up call (see schedule above)',
      sortOrder: 170,
    },
    {
      name: 'text16',
      type: 'text',
      label: 'Job Discussed',
      required: true,
      description: 'tag the job# here for any jobs discussed and whether or not they are interested',
      sortOrder: 170,
    },
    {
      name: 'date3',
      type: 'date',
      label: 'Date NTQ was completed:',
      required: true,
      sortOrder: 180,
      //readOnly: true,
      dateFormat: 'ddd MMM DD, YYYY', // Add this to your MetaData to override the dateFormat
      defaultValue: new Date(Date.now()),
    },
  ],
};  
//     {
//       name: 'address',
//       type: 'address',
//       dataType: 'Address',
//       dataSpecialization: 'SYSTEM',
//       confidential: false,
//       optional: true,
//       label: 'Address',
//       required: true,
//       readOnly: false,
//       multiValue: false,
//       hideFromSearch: true,
//       tooltip: 'Address Block',
//       fields: [
//         {
//           name: 'address1',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 40,
//           confidential: false,
//           optional: true,
//           label: 'Addressxxx',
//           required: true,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//           defaultValue: '100 Summer St',
//         },
//         {
//           name: 'address2',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 40,
//           confidential: false,
//           optional: true,
//           label: 'Address 2',
//           required: false,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//           defaultValue: 'apt 25',
//         },
//         {
//           name: 'city',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 40,
//           confidential: false,
//           optional: true,
//           label: 'City',
//           required: true,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//         },
//         {
//           name: 'state',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 30,
//           confidential: false,
//           optional: true,
//           label: 'State',
//           required: true,
//           readOnly: false,
//           multiValue: false,
//           inputType: 'SELECT',
//           hideFromSearch: false,
//         },
//         {
//           name: 'zip',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 15,
//           confidential: false,
//           optional: true,
//           label: 'Zip',
//           required: true,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//         },
//         {
//           name: 'countryID',
//           type: 'SCALAR',
//           dataType: 'Integer',
//           confidential: false,
//           optional: false,
//           label: 'Country',
//           required: false,
//           readOnly: false,
//           multiValue: false,
//           inputType: 'SELECT',
//           defaultValue: 2260,
//           hideFromSearch: false,
//         },
//         {
//           name: 'countryCode',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 0,
//           optional: true,
//         },
//         {
//           name: 'countryName',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 0,
//           optional: true,
//         },
//       ],
//       sortOrder: 150,
//     },
//     {
//       name: 'date10',
//       type: 'date-time',
//       label: 'date10',
//       dataSpecialization: 'DATETIME',
//       required: true,
//       sortOrder: 1190,
//     },
//     {
//       name: 'date4',
//       type: 'date',
//       label: 'Date',
//       required: true,
//       sortOrder: 240,
//       dateFormat: 'ddd MMM DD, YYYY', // Add this to your MetaData to override the dateFormat
//       defaultValue: new Date(2016, 1, 1),
//     },
//     {
//       name: 'currency',
//       type: 'money',
//       label: 'Cost',
//       currencyFormat: 'USD',
//       sortOrder: 200,
//     },
//     {
//       name: 'percent',
//       type: 'percentage',
//       label: 'Percentage',
//       required: true,
//       sortOrder: 220,
//     },
//     {
//       name: 'date',
//       type: 'date',
//       label: 'Date',
//       required: true,
//       sortOrder: 240,
//       dateFormat: 'ddd MMM DD, YYYY', // Add this to your MetaData to override the dateFormat
//       defaultValue: new Date(2016, 1, 1),
//     },
//     {
//       name: 'time',
//       type: 'time',
//       label: 'Time',
//       required: true,
//       sortOrder: 260,
//     },
//     {
//       name: 'native-time',
//       type: 'native-time',
//       label: 'Native Time',
//       required: true,
//       sortOrder: 280,
//     },
//     {
//       name: 'native-datetime-local',
//       type: 'native-datetime-local',
//       label: 'Native Date Time Local',
//       required: true,
//       sortOrder: 300,
//     },
//     {
//       name: 'datetime',
//       type: 'date-time',
//       label: 'DateTime',
//       dataSpecialization: 'DATETIME',
//       required: true,
//       sortOrder: 350,
//     },
//     {
//       name: 'status',
//       type: 'select',
//       dataType: 'String',
//       maxLength: 200,
//       confidential: false,
//       label: 'Status',
//       options: [
//         {
//           value: 'Open',
//           label: 'Open',
//         },
//         {
//           value: 'Qualifying',
//           label: 'Qualifying',
//         },
//         {
//           value: 'Negotiating',
//           label: 'Negotiating',
//         },
//         {
//           value: 'TRIGGER',
//           label: 'TRIGGER',
//         },
//       ],
//       sortOrder: 400,
//     },
//     {
//       name: 'nextAction',
//       type: 'tiles',
//       dataType: 'String',
//       label: 'Next Action',
//       required: true,
//       options: [
//         {
//           value: 'none',
//           label: 'None',
//         },
//         {
//           value: 'task',
//           label: 'Task',
//         },
//         {
//           value: 'appointment',
//           label: 'Appointment',
//         },
//       ],
//       sortOrder: 450,
//     },
//     {
//       name: 'state',
//       type: 'picker',
//       dataType: 'String',
//       maxLength: 200,
//       confidential: false,
//       label: 'State',
//       required: true,
//       // TODO: Align picker with META by passing META obj into picker
//       // options: [ /* flat array of states */ ]
//       options: {
//         options: [
//           'Alabama',
//           'Alaska',
//           'Arizona',
//           'Arkansas',
//           'California',
//           'Colorado',
//           'Connecticut',
//           'Delaware',
//           'Florida',
//           'Georgia',
//           'Hawaii',
//           'Idaho',
//           'Illinois',
//           'Indiana',
//           'Iowa',
//           'Kansas',
//           'Kentucky',
//           'Louisiana',
//           'Maine',
//           'Maryland',
//           'Massachusetts',
//           'Michigan',
//           'Minnesota',
//           'Mississippi',
//           'Missouri',
//           'Montana',
//           'Nebraska',
//           'Nevada',
//           'New Hampshire',
//           'New Jersey',
//           'New Mexico',
//           'New York',
//           'North Dakota',
//           'North Carolina',
//           'Ohio',
//           'Oklahoma',
//           'Oregon',
//           'Pennsylvania',
//           'Rhode Island',
//           'South Carolina',
//           'South Dakota',
//           'Tennessee',
//           'Texas',
//           'Utah',
//           'Vermont',
//           'Virginia',
//           'Washington',
//           'West Virginia',
//           'Wisconsin',
//           'Wyoming',
//         ],
//       },
//       sortOrder: 530,
//     },
//     {
//       name: 'startDate',
//       type: 'datetime',
//       dataType: 'Timestamp',
//       label: 'Start Date',
//       disabled: true,
//       required: true,
//       sortOrder: 540,
//     },
//     {
//       name: 'quota',
//       type: 'number',
//       dataType: 'Integer',
//       label: 'Quota',
//       required: true,
//       sortOrder: 550,
//     },
//     {
//       name: 'secret',
//       type: 'hidden',
//       dataType: 'String',
//       label: 'Top Secret',
//       required: true,
//       defaultValue: 'The secret code is: 08322',
//       sortOrder: 560,
//     },
//     {
//       name: 'categories',
//       type: 'picker',
//       confidential: false,
//       optional: false,
//       label: 'Categories',
//       required: true,
//       readOnly: false,
//       multiValue: true,
//       inputType: 'SELECT',
//       options: [
//         {
//           value: 'Open',
//           label: 'Open',
//         },
//         {
//           value: 'Qualifying',
//           label: 'Qualifying',
//         },
//         {
//           value: 'Negotiating',
//           label: 'Negotiating',
//         },
//         {
//           value: 'TRIGGER',
//           label: 'TRIGGER',
//         },
//       ],
//       sortOrder: 570,
//     },
//     {
//       name: 'owner',
//       type: 'entity',
//       confidential: false,
//       optional: false,
//       label: 'Owner',
//       required: false,
//       readOnly: true,
//       multiValue: false,
//       inputType: 'SELECT',
//       optionsType: 'CorporateUser',
//       optionsUrl: '/options/CorporateUser',
//       hideFromSearch: false,
//       associatedEntity: {
//         entity: 'CorporateUser',
//         label: 'Corporate User',
//       },
//       sortOrder: 580,
//     },
//     {
//       name: 'address',
//       type: 'address',
//       dataType: 'Address',
//       dataSpecialization: 'SYSTEM',
//       confidential: false,
//       optional: true,
//       label: 'Address',
//       required: false,
//       readOnly: false,
//       multiValue: false,
//       hideFromSearch: true,
//       tooltip: 'Address Block',
//       fields: [
//         {
//           name: 'address1',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 40,
//           confidential: false,
//           optional: true,
//           label: 'Addressxxx',
//           required: true,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//           defaultValue: '100 Summer St',
//         },
//         {
//           name: 'address2',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 40,
//           confidential: false,
//           optional: true,
//           label: 'Address 2',
//           required: false,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//           defaultValue: 'apt 25',
//         },
//         {
//           name: 'city',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 40,
//           confidential: false,
//           optional: true,
//           label: 'City',
//           required: false,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//         },
//         {
//           name: 'state',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 30,
//           confidential: false,
//           optional: true,
//           label: 'State',
//           required: true,
//           readOnly: false,
//           multiValue: false,
//           inputType: 'SELECT',
//           hideFromSearch: false,
//         },
//         {
//           name: 'zip',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 15,
//           confidential: false,
//           optional: true,
//           label: 'Zip',
//           required: false,
//           readOnly: false,
//           multiValue: false,
//           hideFromSearch: false,
//         },
//         {
//           name: 'countryID',
//           type: 'SCALAR',
//           dataType: 'Integer',
//           confidential: false,
//           optional: false,
//           label: 'Country',
//           required: false,
//           readOnly: false,
//           multiValue: false,
//           inputType: 'SELECT',
//           defaultValue: 2260,
//           hideFromSearch: false,
//         },
//         {
//           name: 'countryCode',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 0,
//           optional: true,
//         },
//         {
//           name: 'countryName',
//           type: 'SCALAR',
//           dataType: 'String',
//           maxLength: 0,
//           optional: true,
//         },
//       ],
//       sortOrder: 590,
//     },
//     {
//       name: 'checkbox',
//       type: 'checkbox',
//       label: 'Checkbox',
//       sortOrder: 600,
//     },
//     {
//       name: 'checklist',
//       type: 'checklist',
//       label: 'CheckList',
//       options: ['Morning', 'Day', 'Night', 'Overnight'],
//       required: true,
//       sortOrder: 610,
//     },
//     {
//       name: 'attachments',
//       type: 'file',
//       label: 'Attachments',
//       multiValue: true,
//       required: true,
//       sortOrder: 630,
//     },
//     {
//       defaultValue: 'Cold',
//       inputType: 'RADIO',
//       label: 'Types/Ratings',
//       maxLength: 100,
//       multiValue: false,
//       name: 'type',
//       optional: true,
//       options: [
//         {
//           value: 'Hot',
//           label: 'Hot',
//         },
//         {
//           value: 'Cold',
//           label: 'Cold',
//         },
//         {
//           value: 'Eh...',
//           label: 'Eh...',
//         },
//       ],
//       required: true,
//       sortOrder: 9000,
//     },
//     {
//       inputType: 'RADIO',
//       label: 'Like?',
//       maxLength: 100,
//       multiValue: false,
//       name: 'like',
//       optional: true,
//       options: [
//         {
//           value: 'Yes',
//           label: 'Yes',
//           icon: 'check',
//         },
//         {
//           value: 'No',
//           label: 'No',
//           icon: 'times',
//         },
//       ],
//       required: true,
//       sortOrder: 9000,
//     },
//     {
//       name: 'comments',
//       type: 'textarea',
//       label: 'Comments',
//       required: true,
//       sortOrder: 9010,
//       maxLength: 150,
//       description: 'Comments, Please',
//     },
//     {
//       name: 'address',
//       type: 'address',
//       label: 'Address',
//       required: true,
//       sortOrder: 620,
//     },
//     {
//       name: 'customfield',
//       label: 'Custom Component',
//       required: true,
//       description: 'This is a custom component you can use instead',
//     },
//     {
//       name: 'htmlFieldFullEditor',
//       label: 'CK Editor - Full',
//       required: true,
//       sortOrder: 9011,
//       dataSpecialization: 'HTML',
//       type: 'SCALAR',
//       dataType: 'String',
//     },
//     {
//       name: 'htmlFieldMinimalEditor',
//       label: 'CK Editor - Minimal',
//       required: true,
//       sortOrder: 9012,
//       dataSpecialization: 'HTML-MINIMAL',
//       type: 'SCALAR',
//       dataType: 'String',
//     },
//   ],
// };
export const MockMetaHeaders = {
  sectionHeaders: [
    {
      label: 'Section With Custom Icon',
      name: 'sectionHeader3',
      sortOrder: 600,
      enabled: true,
      icon: 'bhi-certification',
    },
    {
      label: 'Section 2',
      name: 'sectionHeader2',
      sortOrder: 500,
      enabled: true,
    },
    {
      label: 'Section 1',
      name: 'sectionHeader1',
      sortOrder: 45,
      enabled: true,
    },
  ],
};
Object.assign(MockMetaHeaders, MockMeta);
export const MockMetaForDisabledForm = {
  entity: 'ENTITY_NAME',
  entityMetaUrl: '',
  label: 'ENTITY_LABEL',
  fields: [
    {
      name: 'textbox',
      type: 'text',
      label: 'TextBox',
      required: true,
      sortOrder: 500,
      maxLength: 10,
    },
    {
      name: 'textarea',
      type: 'textarea',
      label: 'TextArea',
      required: true,
      sortOrder: 550,
      maxLength: 10,
    },
    {
      name: 'number',
      type: 'number',
      label: 'Number',
      required: true,
      sortOrder: 600,
    },
    {
      name: 'year',
      type: 'number',
      label: 'Year',
      dataSpecialization: 'YEAR',
      required: true,
      sortOrder: 650,
    },
    {
      name: 'float',
      type: 'float',
      label: 'Float',
      required: true,
      sortOrder: 700,
    },
    {
      name: 'currency',
      type: 'money',
      label: 'Currency',
      currencyFormat: 'USD',
      required: true,
      sortOrder: 750,
    },
    {
      name: 'percent',
      type: 'percentage',
      label: 'Percentage',
      required: true,
      sortOrder: 800,
    },
    {
      name: 'date',
      type: 'date',
      label: 'Date',
      required: true,
      sortOrder: 850,
      defaultValue: new Date(2016, 1, 1),
    },
    {
      name: 'time',
      type: 'time',
      label: 'Time',
      required: true,
      sortOrder: 900,
      defaultValue: new Date(2016, 1, 1, 9, 0, 0, 0),
    },
    {
      name: 'datetime',
      type: 'date-time',
      label: 'DateTime',
      dataSpecialization: 'DATETIME',
      required: true,
      sortOrder: 50,
      defaultValue: new Date(2016, 1, 1, 9, 0, 0, 0),
    },
    {
      name: 'select',
      type: 'select',
      dataType: 'String',
      maxLength: 200,
      confidential: false,
      label: 'Select',
      options: [
        {
          value: 'Open',
          label: 'Open',
        },
        {
          value: 'disabledValue',
          label: 'Disabled Value',
        },
      ],
      sortOrder: 100,
    },
    {
      name: 'tiles',
      type: 'tiles',
      dataType: 'String',
      label: 'Tiles',
      required: true,
      options: [
        {
          value: 'None',
          label: 'None',
        },
        {
          value: 'Disabled',
          label: 'Disabled',
        },
        {
          value: 'Enabled',
          label: 'Enabled',
        },
      ],
      sortOrder: 130,
    },
    {
      name: 'picker',
      type: 'picker',
      dataType: 'String',
      maxLength: 200,
      confidential: false,
      label: 'Picker',
      required: true,
      options: {
        options: ['Alabama', 'Alaska', 'Disabled Picker'],
      },
      sortOrder: 80,
    },
    {
      name: 'chips',
      type: 'picker',
      confidential: false,
      optional: false,
      label: 'Chips',
      required: true,
      readOnly: false,
      multiValue: true,
      inputType: 'SELECT',
      options: [
        {
          value: 'Open',
          label: 'Open',
        },
        {
          value: 'Disabled',
          label: 'Disabled',
        },
        {
          value: 'Chip',
          label: 'Chip',
        },
        {
          value: 'TRIGGER',
          label: 'TRIGGER',
        },
      ],
      sortOrder: 150,
    },
    {
      name: 'rowChips',
      type: 'TO_MANY',
      confidential: false,
      optional: false,
      label: 'Row Chips',
      required: true,
      readOnly: false,
      multiValue: false,
      options: [
        {
          id: 1,
          value: 'Disabled Row Chip',
          description: 'This is a disabled Row Chip',
        },
      ],
      hideFromSearch: false,
      sortOrder: 160,
    },
    {
      name: 'address',
      type: 'COMPOSITE',
      dataType: 'Address',
      dataSpecialization: 'SYSTEM',
      confidential: false,
      optional: false,
      label: 'Address',
      required: true,
      readOnly: false,
      multiValue: false,
      hideFromSearch: true,
      tooltip: 'Address Block',
      fields: [
        {
          name: 'address1',
          type: 'SCALAR',
          dataType: 'String',
          maxLength: 40,
          confidential: false,
          optional: true,
          label: 'Address 1',
          required: true,
          readOnly: false,
          multiValue: false,
          hideFromSearch: false,
        },
        {
          name: 'address2',
          type: 'SCALAR',
          dataType: 'String',
          maxLength: 40,
          confidential: false,
          optional: true,
          label: 'Address 2',
          required: false,
          readOnly: false,
          multiValue: false,
          hideFromSearch: false,
        },
        {
          name: 'city',
          type: 'SCALAR',
          dataType: 'String',
          maxLength: 40,
          confidential: false,
          optional: true,
          label: 'City',
          required: false,
          readOnly: false,
          multiValue: false,
          hideFromSearch: false,
        },
        {
          name: 'state',
          type: 'SCALAR',
          dataType: 'String',
          maxLength: 30,
          confidential: false,
          optional: true,
          label: 'State',
          required: true,
          readOnly: false,
          multiValue: false,
          inputType: 'SELECT',
          hideFromSearch: false,
        },
        {
          name: 'zip',
          type: 'SCALAR',
          dataType: 'String',
          maxLength: 15,
          confidential: false,
          optional: true,
          label: 'Zip',
          required: false,
          readOnly: false,
          multiValue: false,
          hideFromSearch: false,
        },
        {
          name: 'countryID',
          type: 'SCALAR',
          dataType: 'Integer',
          confidential: false,
          optional: false,
          label: 'Country',
          required: false,
          readOnly: false,
          multiValue: false,
          inputType: 'SELECT',
          defaultValue: 2260,
          hideFromSearch: false,
        },
        {
          name: 'countryCode',
          type: 'SCALAR',
          dataType: 'String',
          maxLength: 0,
          optional: true,
        },
        {
          name: 'countryName',
          type: 'SCALAR',
          dataType: 'String',
          maxLength: 0,
          optional: true,
        },
      ],
      sortOrder: 10,
    },
    {
      name: 'checkbox',
      type: 'checkbox',
      label: 'Checkbox',
      defaultValue: true,
      sortOrder: 20,
    },
    {
      name: 'checklist',
      type: 'checklist',
      label: 'CheckList',
      options: [
        {
          value: 'None',
          label: 'None',
        },
        {
          value: 'Disabled',
          label: 'Disabled',
        },
        {
          value: 'Enabled',
          label: 'Enabled',
        },
      ],
      required: true,
      sortOrder: 30,
    },
    {
      name: 'file',
      type: 'file',
      label: 'File',
      multiValue: true,
      required: true,
      sortOrder: 70,
    },
    {
      defaultValue: 'disabled',
      inputType: 'RADIO',
      label: 'Radio',
      maxLength: 100,
      multiValue: false,
      name: 'type',
      optional: true,
      options: [
        {
          value: 'none',
          label: 'None',
        },
        {
          value: 'disabled',
          label: 'Disabled',
        },
        {
          value: 'enabled',
          label: 'Enabled',
        },
      ],
      required: true,
      sortOrder: 9000,
    },
    {
      inputType: 'RADIO',
      label: 'Radio',
      maxLength: 100,
      multiValue: false,
      name: 'radio',
      optional: true,
      options: [
        {
          value: 'Yes',
          label: 'Yes',
          icon: 'check',
        },
        {
          value: 'No',
          label: 'No',
          icon: 'times',
        },
      ],
      required: true,
      sortOrder: 9000,
    },
    {
      name: 'htmlFieldFullEditor',
      key: 'htmlFieldFullEditor',
      label: 'Editor',
      required: true,
      sortOrder: 60,
      dataSpecialization: 'HTML',
      type: 'SCALAR',
      dataType: 'String',
    },
  ],
};
export const MockMetaForForm = {
  entity: 'ENTITY_NAME',
  entityMetaUrl: '',
  label: 'ENTITY_LABEL',
  fields: [
    {
      name: 'textbox1',
      type: 'text',
      label: 'TextBox 1',
      required: true,
      sortOrder: 110,
      maxLength: 10,
    },
    {
      name: 'textbox2',
      type: 'text',
      label: 'TextBox 2',
      required: true,
      sortOrder: 120,
      maxLength: 10,
    },
    {
      name: 'textbox3',
      type: 'text',
      label: 'TextBox 3',
      required: true,
      sortOrder: 130,
      maxLength: 10,
    },
  ],
};

